import template from "../../../shared/consent-template.json";
import { areaFromHas, validateDraftFields, type ConsentFormDraft } from "../../../shared/consent-draft";

export const escapeHtml = (s: string) => s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
export function consentPrintHtml(draft: ConsentFormDraft): string {
  const f=validateDraftFields(draft.fields); const area=areaFromHas(f.has);
  const tokens: Record<string,string>={...f,owners:f.owners.join(", "),acres:String(area.acres),guntha:String(area.guntha)};
  const para=(s: string)=>`<p>${escapeHtml(s).replace(/\{\{(\w+)\}\}/g,(_,k:string)=>escapeHtml(tokens[k] || ""))}</p>`;
  const footer=`<footer>Unsigned generated form · ${escapeHtml(draft.id.slice(0,8))} · revision ${draft.revision} · Owner signature and verification pending</footer>`;
  const header=`<div class="meta"><span>Date / તારીખ: ${escapeHtml(f.date)}</span><span>Village / ગામ: ${escapeHtml(f.village_en)} / ${escapeHtml(f.village_gu)}</span></div>`;
  const details=[['સર્વે નં. / Survey No.',f.survey_number],['ખાતા નં. / Khata No.',f.khata],['જમીન માલિકનું નામ / Land Owner',f.owners.join(', ')],['ગામ / Village',`${f.village_en} / ${f.village_gu}`],['તાલુકો / Taluka',f.taluka],['જીલ્લો / District',f.district],['મોબાઈલ નં. / Mobile No.',f.mobile]];
  // Rows and sections flow across printed pages rather than clipping large owner lists.
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="referrer" content="no-referrer"><title>Unsigned consent form — ${escapeHtml(f.village_en)} ${escapeHtml(f.survey_number)}</title><style>
    @page{size:A4;margin:14mm 13mm 16mm}*{box-sizing:border-box}body{margin:0;color:#151515;font:10.2pt/1.42 Arial,"Noto Sans Gujarati",sans-serif}.sheet{break-before:page}.sheet:first-child{break-before:auto}h1{font-size:14pt;text-align:center;margin:0 0 12pt}h2{font-size:11pt;margin:13pt 0 7pt}p{margin:0 0 7pt;orphans:3;widows:3}.meta{display:flex;justify-content:space-between;gap:20pt;font-size:9.5pt;margin-bottom:12pt}table{border-collapse:collapse;width:100%;font-size:10pt}th,td{border:1px solid #444;padding:7pt;vertical-align:top;overflow-wrap:anywhere}tr{break-inside:avoid}thead{display:table-header-group}.owners td{height:40pt}footer{font-size:8pt;color:#555;border-top:1px solid #bbb;margin-top:12pt;padding-top:5pt;break-inside:avoid}.signatures{display:flex;justify-content:space-between;margin-top:18pt;break-inside:avoid;gap:20pt}.stamp{width:140pt;height:75pt;border:1px solid;text-align:center;padding:10pt;font-size:8.5pt}.section-end{break-inside:avoid}ol{padding-left:20pt;line-height:1.7}@media screen{body{background:#eee}.sheet{background:white;max-width:210mm;margin:18px auto;padding:14mm 13mm;box-shadow:0 2px 9px #0002}footer{color:#555}}@media print{.screen-only{display:none}}
    .undertaking{font-size:9.2pt;line-height:1.32}.undertaking p{margin-bottom:5pt}.undertaking .meta{font-size:9pt;margin-bottom:8pt}.undertaking th,.undertaking td{font-size:9pt;padding:4.5pt}.undertaking .signatures{margin-top:12pt}.undertaking .stamp{height:65pt;font-size:8pt}.undertaking footer{margin-top:8pt}
  </style></head><body>
    <section class="sheet"><h1>${escapeHtml(template.consent_title)}</h1>${header}<h2>ENGLISH VERSION</h2>${template.consent_english.map(para).join('')}<h2>GUJARATI VERSION</h2>${template.consent_gujarati.map(para).join('')}${footer}</section>
    <section class="sheet"><h1>Owners / જમીન માલિકો</h1>${header}<table class="owners"><thead><tr><th>No. / ક્રમ</th><th>Name of Owner / Khatedar</th><th>Signature / સહી</th></tr></thead><tbody>${f.owners.map((s,i)=>`<tr><td>${i+1}</td><td>${escapeHtml(s)}</td><td style="width:30%"></td></tr>`).join('')}</tbody></table><div class="section-end"><h2>Khata No. / ખાતા નં.: ${escapeHtml(f.khata)}</h2><h2>Enclosures / જોડવાના દસ્તાવેજો</h2><ol>${template.enclosures.map(s=>`<li>${escapeHtml(s)}</li>`).join('')}</ol>${footer}</div></section>
    <section class="sheet undertaking"><h1>${escapeHtml(template.undertaking_title)}</h1>${header}${template.undertaking_gujarati.map(para).join('')}<hr>${template.undertaking_english.map(para).join('')}<table>${details.map(([label,s])=>`<tr><td style="width:42%"><b>${escapeHtml(label)}</b></td><td>${escapeHtml(s)}</td></tr>`).join('')}</table><div class="signatures"><div>સાક્ષીનું નામ / Witness Name:<br>________________________<br><br>સાક્ષીની સહી / Witness Signature:<br>________________________</div><div><div class="stamp">PASTE REVENUE TICKET HERE<br>(રેવન્યુ સ્ટેમ્પ અહીં ચોંટાડો)</div><p>ખેડૂતની સહી / Farmer’s Signature</p></div></div>${footer}</section>
  </body></html>`;
}
