import { useEffect, useState, type FormEvent } from "react";
import { loadProjectAccounts, manageProjectAccount, type ProjectAccount } from "./api";

const roleNames: Record<string, string> = { admin: "Administrator", editor: "Editor", viewer: "Viewer", commenter: "Commenter", data_entry: "Data entry", legal: "Legal", finance: "Finance" };
function RoleSelect({ value, onChange, label, disabled }: { value: string; onChange: (value: string) => void; label: string; disabled?: boolean }) {
  return <select aria-label={label} value={value} disabled={disabled} onChange={e => onChange(e.target.value)}><option value="viewer">Viewer</option><option value="commenter">Commenter</option><option value="editor">Editor</option></select>;
}
export function UserManagement() {
  const [users, setUsers] = useState<ProjectAccount[]>([]), [roles, setRoles] = useState<Record<string, string>>({});
  const [email, setEmail] = useState(""), [name, setName] = useState(""), [role, setRole] = useState("viewer");
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(""), [message, setMessage] = useState("");
  const [showInvite, setShowInvite] = useState(false), [filter, setFilter] = useState<"pending" | "all">("pending");
  const reload = async () => { setLoading(true); try { const rows = await loadProjectAccounts(); setUsers(rows); setRoles(Object.fromEntries(rows.map(u => [u.id, u.role]))); } catch (failure) { setError(failure instanceof Error ? failure.message : "Could not load accounts."); } finally { setLoading(false); } };
  useEffect(() => { void reload(); }, []);
  const action = async (input: Parameters<typeof manageProjectAccount>[0], success: string) => {
    if (busy) return; setBusy(true); setError(""); setMessage("");
    try { await manageProjectAccount(input); setMessage(success); if (input.action === "invite") { setEmail(""); setName(""); setShowInvite(false); } await reload(); } catch (failure) { setError(failure instanceof Error ? failure.message : "Account action failed."); } finally { setBusy(false); }
  };
  const invite = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); void action({ action: "invite", email, full_name: name, role }, "Invitation sent. Approve the pending account when it is ready to enter the ERP."); };
  const pendingCount = users.filter(u => u.approval_status === "pending").length;
  const rows = users.filter(u => filter === "all" || u.approval_status === "pending");
  return <div className="users-workspace"><section className="page-intro"><div><div className="eyebrow">Administrator</div><h2>Users & access</h2><p>Invite your team and review requests before granting project access.</p></div><button className="button button-primary" disabled={busy} onClick={() => setShowInvite(!showInvite)} type="button">{showInvite ? "Close invitation" : "Invite user"}</button></section>
    <div className="role-guide"><p><strong>Editor</strong> Update consent, workflow, owner details and documents.</p><p><strong>Commenter</strong> View records and add survey notes.</p><p><strong>Viewer</strong> View records and standard reports.</p></div>
    {showInvite && <form className="card invitation-form" onSubmit={invite}><h3>Send an invitation</h3><div className="form-grid"><label>Full name<input value={name} maxLength={100} onChange={e => setName(e.target.value)} autoComplete="name"/></label><label>Email address<input required type="email" maxLength={254} value={email} onChange={e => setEmail(e.target.value)} autoComplete="email"/></label><label>Access role<RoleSelect value={role} onChange={setRole} label="Invitation access role"/></label></div><p className="small-note">The email links to this ERP. Invitations require your approval before the user can enter.</p><button className="button button-primary" disabled={busy} type="submit">{busy ? "Sending…" : "Send invitation"}</button></form>}
    {error && <p className="form-error" role="alert">{error}</p>}{message && <p className="access-message" role="status">{message}</p>}
    <div className="users-toolbar"><div className="workspace-tabs"><button type="button" className={filter === "pending" ? "is-active" : ""} onClick={() => setFilter("pending")}>Pending requests <span>{pendingCount}</span></button><button type="button" className={filter === "all" ? "is-active" : ""} onClick={() => setFilter("all")}>All accounts</button></div><button className="button button-secondary" onClick={() => void reload()} disabled={busy || loading} type="button">Refresh</button></div>
    <section className="card users-card">{loading ? <p role="status">Loading project accounts…</p> : rows.length === 0 ? <div className="users-empty"><h3>No pending requests</h3><p>New account requests will appear here for your review.</p></div> : <div className="table-scroll"><table><thead><tr><th>Account</th><th>Access</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(user => <tr key={user.id}><td><strong>{user.full_name || user.email}</strong><small>{user.email}</small><small>Created {new Date(user.created_at).toLocaleDateString("en-IN")}</small></td><td>{user.role === "admin" ? roleNames.admin : <RoleSelect value={roles[user.id] || "viewer"} onChange={value => setRoles(current => ({ ...current, [user.id]: value }))} label={`Access role for ${user.email}`} disabled={busy}/>}</td><td><span className={`account-status account-${user.approval_status}`}>{user.approval_status}</span></td><td>{user.role === "admin" ? <span className="muted">Protected administrator</span> : <div className="user-actions">{user.approval_status !== "approved" && <button className="button button-primary" disabled={busy} onClick={() => void action({ action: "approve", user_id: user.id, role: roles[user.id] }, "Account approved. The user can now enter the ERP.")} type="button">Approve</button>}{user.approval_status === "pending" && <button className="button button-secondary" disabled={busy} onClick={() => void action({ action: "reject", user_id: user.id, role: roles[user.id] }, "Access request declined.")} type="button">Decline</button>}{user.approval_status === "approved" && <><button className="button button-secondary" disabled={busy || roles[user.id] === user.role} onClick={() => void action({ action: "role", user_id: user.id, role: roles[user.id] }, "Access role updated.")} type="button">Save role</button><button className="button button-secondary" disabled={busy} onClick={() => void action({ action: "suspend", user_id: user.id, role: roles[user.id] }, "Account access paused.")} type="button">Pause access</button></>}</div>}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
