import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {stripTypeScriptTypes} from 'node:module';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
async function harness(config={}) {
 const state={role:'admin',active:true,approval:'approved',fetches:[],...config};let handler;
 const sdk={auth:{getUser:async token=>({data:{user:token==='valid'?{id:'actor'}:null},error:null})},from(table){assert.equal(table,'profiles');return{select(){return this},eq(){return this},maybeSingle:async()=>({data:{role:state.role,is_active:state.active,approval_status:state.approval},error:null})}}};
 const context=vm.createContext({Error,Request,Response,URL,TextEncoder,TextDecoder,Uint8Array,AbortSignal,crypto,Date,JSON,fetch:async(url)=>{state.fetches.push(url);return new Response(JSON.stringify(state.data ?? {'old-1':{surveyNo:'12/1',villageEn:'Bitta',villageGu:'બીટા',dateGenerated:'2026-08-08',khataNo:'0009',has:'1.60.57',taluka:'Abdasa',district:'Kutch',mobile:'',owners:['Old Sample Owner / જૂના નમૂના માલિક'],firstOwner:'Old Sample Owner',status:'sent'}}),{status:state.httpStatus || 200})},Deno:{env:{get:k=>({ALLOWED_ORIGIN:'https://nakulkpadi.github.io',SUPABASE_URL:'https://fixture.invalid',SUPABASE_SERVICE_ROLE_KEY:'fixture'})[k]},serve:f=>handler=f}});
 const mockedSdk=new vm.SyntheticModule(['createClient'],function(){this.setExport('createClient',()=>sdk)},{context});const cache=new Map();
 async function load(path){if(!path.endsWith('.ts'))path+='.ts';if(cache.has(path))return cache.get(path);const m=new vm.SourceTextModule(stripTypeScriptTypes(await readFile(path,'utf8'),{mode:'strip'}),{context,identifier:path});cache.set(path,m);await m.link((s,p)=>s.startsWith('npm:')?mockedSdk:load(resolve(dirname(p.identifier),s)));return m}
 const module=await load(resolve(root,'supabase/functions/legacy-consent-forms/index.ts'));await module.evaluate();
 const language=await load(resolve(root,'apps/web/src/consent-language.ts'));await language.evaluate();const legacy=await load(resolve(root,'apps/web/src/legacy-consent.ts'));await legacy.evaluate();
 return {state,handler,language:language.namespace,legacy:legacy.namespace};
}
const req=(token='valid',origin='https://nakulkpadi.github.io',method='GET')=>new Request('https://fixture.invalid/functions/v1/legacy-consent-forms',{method,headers:{Authorization:'Bearer '+token,Origin:origin}});
test('earlier forms read the fixed old source after approval and never write consent',async()=>{const h=await harness();const r=await h.handler(req());assert.equal(r.status,200);const b=await r.json();assert.equal(b.records[0].status,'sent');assert.equal(b.records[0].fields.khata,'0009');assert.deepEqual(h.state.fetches,['https://bhachunda-solar-default-rtdb.asia-southeast1.firebasedatabase.app/consent-forms.json']);assert.equal(r.headers.get('Cache-Control'),'private, no-store')});
test('forged, viewer, commenter and inactive accounts cannot read earlier owner history',async()=>{for(const c of [{role:'viewer'},{role:'commenter'},{approval:'pending'},{active:false}]){const h=await harness(c);assert.equal((await h.handler(req())).status,403);assert.equal(h.state.fetches.length,0)}const h=await harness();assert.equal((await h.handler(req('forged'))).status,401);assert.equal((await h.handler(req('valid','https://evil.invalid'))).status,403);assert.equal((await h.handler(req('valid',undefined,'POST'))).status,405);assert.equal(h.state.fetches.length,0)});
test('old received labels remain historical and incomplete rows are not silently imported',async()=>{const h=await harness({data:{x:{surveyNo:'1',villageEn:'Bitta',status:'received',firstOwner:'Old owner'}}});const b=await(await h.handler(req())).json();assert.equal(b.records[0].status,'received');assert.equal(b.records[0].fields,null);assert.equal(Object.hasOwn(b.records[0],'received_on'),false)});
test('unavailable history reports an error instead of presenting an empty successful list',async()=>{const h=await harness({httpStatus:403});assert.equal((await h.handler(req())).status,502)});
test('language helpers split both scripts, normalize known places, and require verified owner spellings',async()=>{const {language:l}=await harness();assert.equal(l.placeParts('અબડાસા').en,'Abdasa');assert.equal(l.placeParts('Kutch').gu,'કચ્છ');assert.equal(l.nameParts('નમૂના માલિક / Sample Owner').en,'Sample Owner');assert.equal(l.nameParts('Sample Owner / નમૂના માલિક').gu,'નમૂના માલિક');assert.equal(l.printLanguageIssues({owners:['માલિક'],taluka:'Abdasa',district:'Kutch'}).length,1);assert.equal(l.printLanguageIssues({owners:['Sample Owner / નમૂના માલિક'],taluka:'Abdasa',district:'Kutch'}).length,0)});
test('legacy matching never guesses between villages, rejects ambiguous rows, and uses stable import IDs',async()=>{const {legacy:l}=await harness();const rows=[{id:'a',village_name:'Bhavanipar',survey_number:'12/1'},{id:'b',village_name:'Bitta',survey_number:'12/1'}];assert.equal(l.matchLegacySurvey({village_en:'Bhavanipur',survey_number:'12/1'},rows).id,'a');assert.equal(l.matchLegacySurvey({village_en:'Unknown',survey_number:'12/1'},rows),null);assert.equal(l.matchLegacySurvey({village_en:'Bitta',survey_number:'12/1'},[...rows,rows[1]]),null);assert.equal(await l.legacyDraftId('x'),await l.legacyDraftId('x'));assert.notEqual(await l.legacyDraftId('x'),await l.legacyDraftId('y'))});

test('old day-month-year form dates import accurately and impossible dates stay unimportable',async()=>{const base={surveyNo:'12/1',villageEn:'Bitta',villageGu:'બીટા',khataNo:'9',has:'1.60.57',taluka:'Abdasa',district:'Kutch',mobile:'',owners:['Sample Owner']};const h=await harness({data:{a:{...base,dateGenerated:'08-09-2026'},b:{...base,dateGenerated:'2026-09-08'},c:{...base,dateGenerated:'31-02-2026'}}});const rows=(await(await h.handler(req())).json()).records;assert.equal(rows[0].fields.date,'2026-09-08');assert.equal(rows[1].fields.date,'2026-09-08');assert.equal(rows[2].fields,null);assert.equal(rows[0].date,'08-09-2026')});
